name: Deploy to Staging on AWS ECS

on:
  workflow_dispatch:

jobs:
  deploy-to-ecs:
    name: Deploy to AWS ECS
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env from DOTENV
        run: echo "${{ secrets.DOTENV }}" > .env


      - name: Install BE dependencies
        run: composer install --optimize-autoloader --no-dev --no-scripts

      - name: Install npm dependencies
        run: npm ci

      - name: Generate optimized autoload files
        run: composer dump-autoload --optimize

      - name: Build FE
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
       
      - name: Authenticate to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
      
      - name: Build Docker image
        run: docker build -t laravel-app .

      - name: Tag Docker image
        run: docker tag laravel-app:${{ github.sha }} ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/laravel-app:${{ github.sha }}

      - name: Push Docker image
        run: docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/laravel-app:${{ github.sha }}

